### ISSUE TITLE
Include coloured badges inside table row

### ISSUE THREAD

**Issue by shanaka-rajitha** [h2oai/wave#1006]
# Features

- Display coloured badges on a table row.
- Badges are not clickable.

Design URL for specs : https://xd.adobe.com/view/809c4f44-9861-4f57-978a-e2d3515a426e-d5cf/screen/7fc2c20f-f278-4779-82e9-0f061f6e6f2f/

## Table with badges
![table row with badges](https://user-images.githubusercontent.com/12246331/133772551-efd22c80-5789-48b5-bb2d-c4da199ecf6e.jpg)

**Comment by mturoci** [comment]
Correct design link - https://xd.adobe.com/view/809c4f44-9861-4f57-978a-e2d3515a426e-d5cf/screen/7fc2c20f-f278-4779-82e9-0f061f6e6f2f/

@shanaka-rajitha I think we should stick with a single badge design, see #974. Or is there any special reason for doing a new one?

**Comment by shanaka-rajitha** [comment]
Hi @mtanco The alert badges stand prominence over the other sections and information badges, the purpose served is different. There will be instances we will have both alert and information badges on the same information row. Mainly this is more of a visual requirement.

**Comment by mturoci** [comment]
As discussed on Slack, since the prominence lies in colors which are configurable (implemented in #989), we will go for reusing the same tag component in both `ui.table` and `ui.form_card` (#1005) style wise. The only difference is going to be in size of the tag which will be greater in form_card compared to table. Closing this issue since table part is already implemented in #989 and form part will be done in #1005.
