### ISSUE TITLE
Allow sidepanel to be blocking

### ISSUE THREAD

**Issue by Nayananga** [h2oai/wave#1093]
#### Wave SDK Version, OS

(e.g. 0.18.0, OSx)

#### Actual behavior

When a user interaction on a dialog box on top of ui.sde_panel, ui.side_panel closes immediately. If ui.side_panel configured to fire a `dismissed` event, dismissed event also triggered. So ui.side_panel' `dismissed` event is also hard to handle.

https://user-images.githubusercontent.com/25351304/139196754-da60423f-9ddc-41b4-9bce-4dc08808713a.mov

#### Expected behavior

I think it is best to close ui.side_panel only if a certain action executes `q.page['meta'].side_panel = None` or clicking on Side Panel's close button. So `dismissed` event wont trigger unexpectedly

#### Steps To Reproduce

```py
# Meta / SidePanel
# Display a #sidePanel. #meta
# ---
from h2o_wave import main, app, Q, ui


@app('/demo')
async def serve(q: Q):
    if not q.client.initialized:
        q.page['meta'] = ui.meta_card(box='')
        q.page['example'] = ui.form_card(box='1 1 11 10', items=[
            ui.button(name='show_side_panel', label='Order donuts', primary=True)
        ])
        q.client.initialized = True
    else:
        if q.args.show_side_panel:
            q.page['meta'].side_panel = ui.side_panel(title='Welcome to store', items=[
                ui.text('Donuts cost $1.99. Proceed?'),
                ui.buttons([ui.button(name='next_step', label='Next', primary=True)])
            ])
        elif q.args.next_step:
            q.page['meta'].dialog = ui.dialog(
                title='my_dialog',
                items=[
                    ui.text('You will be charged $1.99. Proceed?'),
                    ui.buttons([
                        ui.button(name='cancel', label='Back to safety'),
                        ui.button(name='submit', label='Place order', primary=True),
                    ])
                ]
            )
        elif q.args.submit:
            q.page['example'].items = [ui.message_bar('success', 'Order placed!')]
            q.page['meta'].dialog = None
            q.page['meta'].side_panel = None

        elif q.args.cancel:
            q.page['example'].items = [ui.message_bar('info', 'Order canceled!')]
            q.page['meta'].dialog = None

    await q.page.save()

```

**Comment by marek-mihok** [comment]
The issue is resolved by adding `blocking` property to side panel. Now the `dismissed` event is not triggered when clicking outside of side panel when `blocking=True` is specified. However the new implementation won't work for your specific example where side panel is overlapped by dialog. You should avoid implementing multiple overlays in your application as @mturoci has mentioned.

**The blocking property works as follows:** 
_True to prevent closing when clicking or tapping outside the side panel. Prevents interacting with the page behind the side panel. Defaults to False._

**See the examples below:**

- `blocking=False` (default)

   https://user-images.githubusercontent.com/23740173/149329423-6e639d94-c908-4ee5-b8c8-fed3d47ae230.mov

- `blocking=True`

   https://user-images.githubusercontent.com/23740173/149329460-6728331e-8d20-4265-96ea-9533d0499f25.mov


Please note that the changes were made also to [dialog](https://github.com/h2oai/wave/blob/master/ui/src/dialog.tsx) where already existing `blocking` property now matches the same behaviour as on side panel examples above. 

**Now the dialog's blocking property works as follows:**
_True to prevent closing when clicking or tapping outside the dialog. Prevents interacting with the page behind the dialog. Defaults to False._
