### ISSUE TITLE
Date Picker UI off by 1 Value

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1098]
#### Wave SDK Version, OS
Wave 0.18.0, tested running in OS X and Linux (AI Cloud), safari & chrome

#### Actual behavior
When selecting a date using the `ui.date_picker` component, the UI shows the day _before_ whatever is selected. The value inside of `q.args.date_picker_name` is correct meaning the end user can work around this by remaking the card with the selected value.

#### Expected behavior
The date clicked is the date showed in the UI

#### Steps To Reproduce
Run this app with the 0.18.0 Server and API. Then, select any date (say October 5th), note that the day before (October 4th) is shown. Click the button and see that the expected date is then shown (as October 5th, not 4th, is actually saved, the wrong date is just being shown).

```python
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):

    if q.args.save:
        
        q.page["form"] = ui.form_card(
            box="4 1 4 2",
            items=[
                ui.date_picker(name='start_date', label='Start Date', value=q.args.start_date),
                ui.button(name='save', label='Save Date', primary=True),
            ]
        )

    else:
        q.page["form"] = ui.form_card(
            box="4 1 4 2",
            items=[
                ui.date_picker(name='start_date', label='Start Date'),
                ui.button(name='save', label='Save Date', primary=True),
            ]
        )
    await q.page.save()
```

**Comment by aalencar** [comment]
Hi @mtanco,

I couldn't reproduce the bug either on Chrome or Safari.

I did the following: 

1. git checkout tag 0.18
2. make all
3. run the wave app you provided above

Am I missing any step?

**Comment by mturoci** [comment]
@aalencar bugs, in general, should be reproducible on the current master, no need to checkout past tags.

**Comment by aalencar** [comment]
> Run this app with the 0.18.0 Server and API

@mturoci I see. How do I run a specific version of the Server and API?

**Comment by lo5** [comment]
@aalencar This bug can be reproduced on `master`.

> How do I run a specific version of the Server and API?
Either checkout and `make all` like you did, or download and run a release (quicker).

**Comment by aalencar** [comment]
Ok, I will take a look again. I must have missed something, thanks.

**Comment by mtanco** [comment]
@lo5 I just had a working session with @aalencar and was not able to reproduce on his computer. We looked at wave 0.19.0 specifically (which has this same bug on my machine). 

We are both on OS X and both tested python 3.7.

**Comment by lo5** [comment]
Probably because of local-to-UTC conversion, and you're in different time zones? :-)

**Comment by lo5** [comment]
The bigger problem here is that the date picker should be sending the UTC date, not local date, and apps should be interpreting the dates as UTC.

**Comment by aalencar** [comment]
> If the date picker is providing a valid date d, it's passed to formatDate(), and then setValue() is called with new Date() (why?!).

We must pass down a `Date` object to `Fluent.DatePicker`

> new Date('2021-11-10') would interpret it as UTC (because it assumes UTC if the TZ is missing) and turns it into Nov 9 2021

At the core, `Date` keeps time in UTC but when converting to string, the human-readable local-time version is used.

From `Fluent.DatePicker`'s source code, [Date.toDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString) display the date in local-time.
![image](https://user-images.githubusercontent.com/15820796/141326186-290a3523-1e23-4bd8-a6cd-14f4334c403f.png)

Since @mtanco's timezone is behind UTC (GMT-8) `Fluent.DatePicker` converts whatever date and time to her timezone.

> The bigger problem here is that the date picker should be sending the UTC date, not local date, and apps should be interpreting the dates as UTC.

Our problem is using a `Date` object (which represents time) to represent only the date.
If we don't care about the time in a Date Picker component then I assume that it's OK to create the date and set the time as `00:00:00`, by doing so we make sure the proper day is displayed.

Additional resources:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
https://www.digitalocean.com/community/tutorials/understanding-date-and-time-in-javascript
