### ISSUE TITLE
Footer improvements

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1119]
![image](https://user-images.githubusercontent.com/64769322/141105034-751c7942-34bf-4ec2-b98f-a62e509a58c7.png)

[design url](https://xd.adobe.com/view/acfb7ef1-5b99-4129-97b2-b30f8086c239-f9a8/)

## Proposed API

```ts
/** Create a footer link leading to other internal / external pages. */
interface FooterLink {
  /** The text to be displayed. If blank, the `path` is used as the label. */
  label?: S
  /** The path or URL to link to. */
  path?: S
  /** Where to display the link. Setting this to an empty string or `'_blank'` opens the link in a new tab or window. */
  target?: S
  /** An identifying name for this component. Use this for Wave related routing. Mutually exclusive with path. */
  name?: S
  /** An icon to display next to the label. */
  icon?: S
}

/** Create a collection of footer links. */
interface FooterLinkGroup {
  /** The name of the link group. */
  label: S
  /** The link groups contained in the header. */
  items: FooterLink[]
}

/**
 * Render a page footer displaying a caption.
 * Footer cards are typically displayed at the bottom of a page.
 */
interface State {
  /** The caption. Supports markdown. **/
  caption: S
  /** The card’s image, displayed in the top left corner. */
  image?: S
  /** The navigation groups displayed to the right of the image. */
  items: FooterLinkGroup[]
}
```

**Comment by mturoci** [comment]
Been also thinking if we even need the `image` prop since `caption` supports markdown.

**Comment by lo5** [comment]
The footer design seems more suited for web _sites_ rather than web _apps_. We might be better off making it a bit more modular to satisfy different requirements. 

The `items[]` seems like a good idea, but instead of limiting columns of links, maybe we can:
- Use the existing `ui.link()` instead of the proposed `FooterLink`
- Rename `FooterLinkGroup` to a "list of links" (`ui.links()`?) and make it a `Component`.
- Change `items: FooterLinkGroup[]` to `items: Component[]`

This way, the footer above can be re-created as-is, but also leaves it open-ended for other kinds of footers (for authors that need, say, progress bars, status bars, etc.).

> Been also thinking if we even need the image prop since caption supports markdown.

Yes, markdown should cover that need.
