### ISSUE TITLE
Inactivity Timeout for Auth

### ISSUE THREAD

**Issue by g-eoj** [h2oai/wave#1270]
#### Is your feature request related to a problem? Please describe

For security certification, we need to provide a mechanism to log out users after a defined period of inactivity.

**Comment by mtanco** [comment]
**User Stories:**
As a security admin, I want to ensure that sensitive information is not accessed because an end-user left a screen up. 
As an end user, I want to be able to access the results of jobs which may take a long time to run. 
   - **Information Needed: ** If a user has not interacted with the app for 30 minutes, but the app has long running jobs still running, does this count as idle? If a user is logged out, should background processes be killed? 

**Requirements:**
* A new flag when running the Wave server which will cause **all apps deployed with this server to have this feature**
* The default value of this flag (-1) is that there is no logout time
* The number used in this flag is the number of minutes that can pass that a browser does not interact with the app 
* When that number is hit, the `-oidc-end-session-url` should be called for that user to log them out

**Requirements for an App Developer to use this feature:**
* Running the App Server using SSO 
* The `-oidc-end-session-url` must be set so that the server knows how to log users out


**Related Notes:**
By looking at example Wave Server logs, I think we have all the necessary information for this today - we have time stamps, the id / key for each browser / and the app route that they visited 

```
2022/02/28 12:12:23 # {"addr":"[::1]:49307","route":"/","t":"ui_add"}
2022/02/28 12:12:23 # {"addr":"[::1]:49307","route":"/aaafe0e3-fdc0-4159-95e5-371dda7ffa69","t":"ui_add"}
2022/02/28 12:12:23 * /aaafe0e3-fdc0-4159-95e5-371dda7ffa69 {"d":[{"k":"temp","d":{"view":"form","box":"1 1 1 1","items":[{"text":{"content":"naw"}}]}}]}
2022/02/28 12:12:36 # {"addr":"[::1]:49312","route":"/","t":"ui_add"}
2022/02/28 12:12:36 # {"addr":"[::1]:49312","route":"/a8d7db00-e983-4770-b882-c625dbbd97d0","t":"ui_add"}
2022/02/28 12:12:36 * /a8d7db00-e983-4770-b882-c625dbbd97d0 {"d":[{"k":"temp","d":{"view":"form","box":"1 1 1 1","items":[{"text":{"content":"naw"}}]}}]}
```

**Comment by g-eoj** [comment]
Inactive means no user interaction with the server for x amount of time. Timing out at the server level is fine. We just need to be able to say the server will logout the user after x amount of time. The app/server should continue to run but the user will need to login again to access it.

Here's how the wave app/server will be run:
- wave server in a container
- wave will be configured for oidc
- only one app will be mounted to the container for the server to "pick up"

**Comment by lo5** [comment]
Slated for v0.22:

Set `-session-expiry` to set session expiration lifetime.
Set `-session-inactivity-timeout` to set inactivity timeout.

See `-help` for duration format.

Note that inactivity is tracked across all open tabs, and *all* tabs will redirect to logout on timeout. Redirects to the OIDC provider's end-session URL if set, else redirects to the base URL. Verified against Keycloak.
