### ISSUE TITLE
Timeout doesn't work in notification_bar

### ISSUE THREAD

**Issue by fatihozturkh2o** [h2oai/wave#1353]
#### Wave SDK Version, OS

Wave 0.21, MacOS

### Actual behavior

I've been playing with this new notification_bar component and it seems quite handy! The issue is, whenever I pass a "timeout" value in the component, the notification card pops-up and disappears so quickly. It doesn't stay for time length passed via "timeout"

###  Expected behavior

I'd expect notification bars to stay for the time length passed via "timeout" attribute

### How does it look?

https://user-images.githubusercontent.com/70659545/163599739-14c9f36a-81d0-4e3b-82a0-844932ba53b1.mov

### Steps To Reproduce

You can run the following code to create the issue:

```
from h2o_wave import main, app, Q, ui


@app('/demo')
async def serve(q: Q):
    if not q.client.initialized:
        q.page['form'] = ui.form_card(box='1 1 2 2', items=[
            ui.button(name='top_right', label='Success top-right'),
            ui.button(name='top_left', label='Warning top-left'),
            ui.button(name='top_left_10secs', label='Warning top-left 10s'),
        ])
        q.client.initialized = True
    if q.args.top_right:
        q.page['meta'] = ui.meta_card(box='', notification_bar=ui.notification_bar(
            text='Success notification',
            type='success',
            position='top-right',
            buttons=[ui.button(name='btn1', label='Button 1', link=True)]
        ))
    if q.args.top_left:
        q.page['meta'] = ui.meta_card(box='', notification_bar=ui.notification_bar(
            text='Warning notification',
            type='warning',
            position='top-left',
        ))
    if q.args.top_left_10secs:
        q.page['meta'] = ui.meta_card(box='', notification_bar=ui.notification_bar(
            text='Warning notification',
            type='warning',
            position='top-left',
            timeout=10,
        ))
    await q.page.save()
```

### Questions

I have also realized that, when you pass a "button" in the "buttons" attribute of a "notification_bar", the notification card does not disappear until I click "X". I'd expect them to be disappeared after the time length of "timeout" tbh. This might be also a bug but since I'm not sure if it's the way it was intended, just bringing it up as an extra question. You can observe this in the same video/code above.

**Comment by mturoci** [comment]
>The issue is, whenever I pass a "timeout" value in the component, the notification card pops-up and disappears so quickly

Oops, seems like I forgot to make conversion from `ms` to `s`. For the code above, using `5000` instead of `5` should be a tmp workaround until the next version. => Will fix.

>I have also realized that, when you pass a "button" in the "buttons" attribute of a "notification_bar", the notification card does not disappear until I click "X". I'd expect them to be disappeared after the time length of "timeout" tbh. This might be also a bug but since I'm not sure if it's the way it was intended, just bringing it up as an extra question. You can observe this in the same video/code above.

Yes, that's by design - if `buttons` are present, it indicates a user action is needed and we do not want to hide the notification before they have a chance to perform the action. See the [docs](https://wave.h2o.ai/docs/widgets/overlays/notification_bar/)

![image](https://user-images.githubusercontent.com/64769322/163946762-c00fffb8-f0e8-4b14-ae03-3ed3dd5c8f75.png)

**Comment by Far0n** [comment]
> Yes, that's by design - if `buttons` are present, it indicates a user action is needed and we do not want to hide the notification before they have a chance to perform the action. See the [docs](https://wave.h2o.ai/docs/widgets/overlays/notification_bar/)

@mturoci I see that this behavior is intentional in its current form. But why not giving the programmer the control here. He could still achieve the current behavior by setting timout to -1 or None. Wondering, because we have a use-case where we actually want the notification to disappear when the user did not take any action after N seconds.

**Comment by mturoci** [comment]
> could still achieve the current behavior by setting timeout to -1

I think there would be no harm in doing that. Tracked in https://github.com/h2oai/wave/issues/1366
