### ISSUE TITLE
ui.image excessive debug logging

### ISSUE THREAD

**Issue by gaborfodor** [h2oai/wave#1453]
#### Wave SDK Version, OS

21.0, MacOS 12.

#### Actual behavior

Using `ui.image` with `image=image_data` logs the entire base64 encoded image.
It could cause slow response or even timeout. Server logs become flooded.

#### Expected behavior

The image data could be truncated to not flood the logs.

#### How to reproduce the issue
https://wave.h2o.ai/docs/examples/image

**Comment by vopani** [comment]
@mturoci Is there a simple solution for this? Experiencing this with some other components too (plot related).

**Comment by mturoci** [comment]
>It could cause slow response or even timeout

Can you elaborate?

> Is there a simple solution for this? Experiencing this with some other components too (plot related).

Wave has 2 server parts:
* Wave server - Go - these are the logs that you mention. These log all the browser - server traffic.
* App server - almost no logs other than a request to the app was fulfilled.

I assume you use logs for development / debugging purposes. In that case you have 2 options:
* Use proper [debugging tools](https://wave.h2o.ai/docs/development/#debugging-apps) within your IDE - superior.
* If you still want to use the print statements, but would like to see them more clearly, turn off the Wave server logging via setting `H2O_WAVE_NO_LOG=1` (see [docs](https://wave.h2o.ai/docs/configuration/) for more info).

General answer:

I don't see a strong reason to blacklist some of the data logged since:

* It would make debugging in prod harder as the logs would be incomplete.
* Wave allows restoring state from logs so this feature would break.

**Comment by vopani** [comment]
Just for reference, a similar discussion: https://github.com/h2oai/wave/issues/1374
