### ISSUE TITLE
When button is rendered as a link, it is not right-clickable nor one can copy hyperlink

### ISSUE THREAD

**Issue by ShehanIshanka** [h2oai/wave#1572]
#### Wave SDK Version, OS

0.21.1

#### Actual behavior

https://user-images.githubusercontent.com/29954570/182899869-dff94180-c528-4c0d-ab0f-902606064a5a.mov

#### Expected behavior

Ability to open the link in new tab, new window, copy the link etc.

**Comment by mturoci** [comment]
@ShehanIshanka the feature you want is available when using `ui.link` instead of `ui.button`. To add more clarity:

`ui.button` with `link=True` means - render a button that looks like a link, but unlike regular `ui.link` it should only be used for a wave-specific hash navigation (`#page1`), in other words like a regular Wave button with different styling. This is not possible with `ui.link` as these are meant for regular URLs (`https://...`).

Thus everything is working as expected.

**Comment by ShehanIshanka** [comment]
@mturoci Thanks for the response and solution.
