### ISSUE TITLE
ui.Table: cell content wrap can lead to vertical scrollbar 

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#1646]
#### Wave SDK Version, OS

wave 0.23.1

#### Actual behavior

Cell overflow = `wrap` can lead to "ugly" scrollbar on a ui.table, if table height wasn't set by user to offer enough vertical space.
![grafik](https://user-images.githubusercontent.com/6949295/193000610-fc47f488-9cb4-446f-a8c9-9d0cbc5a7a42.png)

#### Expected behavior

Wave should adjust the height of the table accordingly (if applicable)  to account for the addional needed space due to the wrap.

#### Steps To Reproduce

```python

from h2o_wave import main, app, Q, ui


@app("/")
async def serve(q: Q):
    columns = [
        ui.table_column(
            name="col1",
            label="C1",
            cell_overflow="wrap",
            cell_type=ui.markdown_table_cell_type(name="markdown_type"),
        )
    ]
    rows = [
        ui.table_row(name="row1", cells=["afsdf fsf fs fsdfs fsdf sf sdfsd dsf sfs sd sfs dsf s"])
    ]
    table = ui.table(name="table", columns=columns, rows=rows)
    q.page["form"] = ui.form_card(box="1 1 -1 3", items=[table])
    await q.page.save()
 ```

**Comment by mturoci** [comment]
This behavior is intentional. The reason is being no simple and performant way for checking the wrap - most probably will not be implemented as not worth increasing the code complexity. Static row height is currently used for computing the total table height (if not specified explicitly).

We assume app devs will know best what the expected length of the data is and can adjust the height accordingly.

Additionally, there is a `cell_overflow` type that can be of help as well.

**Comment by Far0n** [comment]
@mturoci would it be possible to allow min_height, max_height for a table as alternative?

**Comment by mturoci** [comment]
In case of an empty table you have 2 options IMO:

* Do not show the table at all.
* Specify the `height` irrespective of the data count (probably better).

Specifying height is also preferred due to layout shift. If you tend to have a dynamic data count, you most likely do not want to have other elements jumping around when it changes. With height set, you either display all rows or get vertical scrollbar for free when rows cannot fit within the table view.

**Comment by Far0n** [comment]
Should be close this issue then?

**Comment by Far0n** [comment]
> If you are happy with my proposed solution then we can close it. Otherwise we can continue in the discussion so that I become more familiar with your usecase.

Your explanations make sense to me.
