### ISSUE TITLE
Is there docker-compose for development in container?

### ISSUE THREAD

**Issue by italanchan** [h2oai/wave#1699]
Hi, 

We want try to develop H2o wave application, is there docker-compose sample to set up development enviornment?

Program language: Python.
IDE: VSCode

**Comment by mturoci** [comment]
Hi @italanchan. 

We do not have a such sample, but it should be trivial to build yourself since Wave's only dependency is Python 3.7 which means all you need is [python base image](https://hub.docker.com/_/python). You are good with just plain docker (no need for docker-compose) for simple Wave apps development.

Also note that the dockerfile should be no different from the ones that are used for e.g. Django, Flask, or any other mainstream python framework.

**Comment by mturoci** [comment]
Added sample project showcasing developing Wave apps within a container - https://github.com/h2oai/wave-apps/tree/main/docker-development.
