### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by Boadzie** [h2oai/wave#1752]
h2o_wave.core.ServiceError: Request failed (code=413): Request Entity Too Large

**Comment by mturoci** [comment]
Hi @Boadzie. This happens when you simply send too much data to the browser. The solution is to either chunk the data (recommended) - think about whether you really need to display them all or increase `H2O_WAVE_MAX_REQUEST_SIZE` - `maximum allowed size of HTTP requests to the server (e.g. 5M or 5MB or 5MiB) (default "5M")`

See [docs](https://wave.h2o.ai/docs/configuration/) for more info.

**Comment by Boadzie** [comment]
Thanks so much for the prompt response

**Comment by Boadzie** [comment]
It working now thanks.

**Comment by mturoci** [comment]
I will make sure the message I linked above appears when users hit this error as it's very common and also quite confusing. Thanks for the question @Boadzie!
