### ISSUE TITLE
OIDC integration does not log error messages

### ISSUE THREAD

**Issue by codyharris-h2o-ai** [h2oai/wave#1761]
#### Wave SDK Version, OS

linux-amd64, 0.24.2

#### Actual behavior

A failed OIDC token exchange does not log the error message, for example cases where the client secret has changed.

#### Expected behavior

Log the error detailed.

#### Steps To Reproduce

1. Launch an app with OIDC integration enabled
2. Intentionally misconfigure the client secret
3. Visit the app

**Comment by mturoci** [comment]
We might need to hop on a call, because I am not able to repro this. I tried:

* Run Wave server with correct secret initially, log in - all is fine, regenerate secret, log in again - server properly logs err message and returns 500.
* Run Wave server with incorrect secret initially, log in - err is logged and 500 returned.

Maybe I am missing something?

![image](https://user-images.githubusercontent.com/64769322/207526461-21d081e6-1b35-491f-a326-09f767365f1f.png)

**Comment by codyharris-h2o-ai** [comment]
@mturoci, an error log is produced, but the upstream error message is not surfaced (the value of `err`).
