### ISSUE TITLE
Improve docs regarding import of 'main'

### ISSUE THREAD

**Issue by spencerchubb** [h2oai/wave#1804]
I spent so long banging my head against the wall, and I feel like a clarification in the docs could help others.

In all the tutorials, you import a variable called 'main' but never actually use the variable. I thought it was weird, so I just removed the import. After many hours, I realized that it is very necessary to import main...

I have never seen an API that requires importing a variable but not using the variable. In fact, most linters will say this is an error. I think because of this non-standard API choice, the tutorials should warn people that 'main' MUST be imported for apps to be served properly.

**Comment by mturoci** [comment]
Thanks for reporting @spencerchubb! The main is being imported so that we can hack around Uvicorn requiring `if __name__ == main` as an entry point. If you are familiar with [marker interface](https://en.wikipedia.org/wiki/Marker_interface_pattern), this is very similar and can be called a "marker import".

While I agree the unused import is non-standard, it's the best we can do. Any PR that could make it better is more than welcome.

Meanwhile, do you have any suggestions on where this should be included in the docs to save time and prevent head injuries from banging against the wall? :)

**Comment by spencerchubb** [comment]
Perhaps in the 'Apps' section of the docs would be a good place to put it? Since it seems to be required for apps but not for scripts

https://wave.h2o.ai/docs/apps

Something like this:
```
# Note: main must be imported even though it is not used
from h2o_wave import main, app, Q, ui

@app('/foo')
async def serve(q: Q):
    # Modify the page
    q.page['qux'] = ui.some_card()

    # Save the page
    await q.page.save()
```

**Comment by mturoci** [comment]
Yes, that sounds reasonable. Would you mind opening a PR yourself?
