### ISSUE TITLE
File upload not working when waved run separately.

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#2225]
#### Wave SDK Version, OS

1.0.0

#### Actual behavior

Files uploaded via q.site.upload are returning 404

#### Expected behavior

(A clear and concise description of what you expected to happen.)

#### Steps To Reproduce

Could not reproduce myself. @marek-mihok please connect to @JohnM-H2O and @kaz-Anova to get a proper repro.

**Comment by marek-mihok** [comment]
The issue is present for file downloads as well and it was not reported when [copy upload](https://github.com/h2oai/wave/pull/1765) is disabled: `H2O_WAVE_NO_COPY_UPLOAD=1`.

The problem is that in some scenarios, `H2O_WAVE_WAVED_DIR` has a wrong value and therefore files are uploaded into a wrong folder. When waved is run separately, we set `H2O_WAVE_WAVED_DIR` value from `sys.exec_prefix` [here](https://github.com/h2oai/wave/blob/7887ef65cf037aea5cc6e845ea8a3193ccdb8261/py/h2o_wave/h2o_wave/cli.py#L179C57-L179C57) which points to location where python executable files are located and this location does not always correspond to actual location from which `./waved` was run from. 

When I run waved separately from venv folder and I don't have virtual environment activated, it points to `/Users/my_user_name/anaconda3`. When I activate virtual environment, it works as it should. Please see the following behavior:

https://github.com/h2oai/wave/assets/23740173/282ef075-7f4d-4409-83cf-59726a630fce

However if waved is run from other than virtual environment folder, it does not work in any of these cases:

https://github.com/h2oai/wave/assets/23740173/c8cfa824-56c2-4257-a158-8787350fa250

The solution could be always specifying `H2O_WAVE_WAVED_DIR` manually to enable copy upload but this solution lacks user convenience. 

Another solution could be for go server to create a temporary file on startup with its working dir location and this file can later be accessed by the wave app (`os.TempDir()` on the go side and `tempfile.gettempdir()` on the python side - it should work consistently across all platforms, however go warns that _The directory is neither guaranteed to exist nor have accessible permissions._).

The third option can be a network request from python asking go for waved location.

@mturoci please let me know which one you think is the best. I've already tried a second option at least on macOS and it's looking good.

**Comment by mturoci** [comment]
Thanks for the investigation @marek-mihok!

Could we set `H2O_WAVE_WAVED_DIR` only during `autostart`? Wouldn't it be enough? That way, separate waved would mean HTTP uploads/downloads, which is fine. Alternatively, if we want to be too smart, we could maybe find the waved cwd by looking at its process id (or something along those lines), but I am not sure whether would work on Windows.

> When I run waved separately from venv folder and I don't have virtual environment activated, it points to /Users/my_user_name/anaconda3. When I activate virtual environment, it works as it should. Please see the following behavior:

This is expected. It should point to current active python, which in your case is activated conda env.

**Comment by marek-mihok** [comment]
> Alternatively, if we want to be too smart, we could maybe find the waved cwd by looking at its process id (or something along those lines), but I am not sure whether would work on Windows.

@mturoci yes, it works, `psutil` does the job! Successfully tested on my Windows machine.
