### ISSUE TITLE
Conda install works with python 3.11 only

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#2227]
#### Wave SDK Version, OS

1.0.0

#### Actual behavior

Running

```sh
conda create -n venv
conda activate venv
conda config --append channels conda-forge
conda install -c h2oai h2o-wave
```

results in Module not found err when trying to use `wave` command.

Using python 3.11 on the other hand works as expected

```sh
conda create -n venv python=3.11
conda activate venv
conda config --append channels conda-forge
conda install -c h2oai h2o-wave
```

#### Expected behavior

Should work python >= 3.8 as specified [here](https://github.com/h2oai/wave/blob/7887ef65cf037aea5cc6e845ea8a3193ccdb8261/py/h2o_wave/pyproject.toml#L8).

**Comment by marek-mihok** [comment]
The reason is there are no python version specific package files on [conda servers](https://anaconda.org/h2oai/h2o-wave/files) as there are present for previous versions of wave. 

Looking at the dates between last two releases (22. september and 10. october) there are 2 suspicious commits that could introduce this change:
https://github.com/h2oai/wave/commit/a476d7d69f98e85cb00179573c3a07eb9ddb38e2 
https://github.com/h2oai/wave/commit/4e03645abfa2b939aa9fb46603f416b37ba357f1

I'm investigating further...

**Comment by mturoci** [comment]
Are you trying to say that previous release works on python 3.8 - 3.12?
