### ISSUE TITLE
Table content overlaps when we use height and tooltip together

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [h2oai/wave#326]
**Q SDK Version, OS**
0.9.1

**Actual behavior**

I’m using a table inside a form_card which is the only component of that particular page. I want the table to be expanded to take a full-page width and height. When I add a tooltip to the page content gets overlapped and the table component won’t be displayed properly. Without the tooltip, it works fine. 

<img width="1581" alt="Screenshot 2020-11-25 at 16 07 20" src="https://user-images.githubusercontent.com/5285626/100225745-b5d74e00-2f44-11eb-87d8-485666559dee.png">

**Expected behavior**
Table content should be extended to the full component.
<img width="1581" alt="Screenshot 2020-11-25 at 16 07 54" src="https://user-images.githubusercontent.com/5285626/100225833-d43d4980-2f44-11eb-939b-409f25557337.png">

**Steps To Reproduce**
1. Use the table component inside the form_card with the below properties.

```py
q.page["risk_table"] = ui.form_card(box="1 2 -1 -1", items=[
  ui.table(
    name='risk_table',
    columns=get_column_headers_for_df(df, True),
    rows=get_rows(q, df),
    groupable=True,
    resettable=True,
    multiple=False,
    height='100%',
    tooltip='Double click a row to go to select it.'
  )
])
```

2. Access the app URL in the browser.

**Comment by mturoci** [comment]
Related https://github.com/h2oai/wave/discussions/879

**Comment by marek-mihok** [comment]
UPDATE: The current situation is that since [this commit ](https://github.com/h2oai/wave/commit/3c574941f37b0e5294e522e2c013c3256ecf3a34) percentage units for height are not working neither with or without a tooltip.

Since using percentage units especially in flex layouts can be tricky, we will provide a new mechanism for table to fill all of the available height - by setting the `height='1'` prop, similar to `ui.inline` or `ui.copyable_text`.

Tracked in #2013

**Comment by mturoci** [comment]
Closing this as completed since #2014 allowed for rendering table to the full card size via `height='1'` instead of `height='100%'` + also works with tooltip.
