### ISSUE TITLE
Loading spinner on UI does not go away if app does not respond

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#357]
**Q SDK Version, OS**
Wave 0.10.0 
Mac OSX

**Actual behavior**
The `@app` function must do something to the site for the automatic loading screen to go away

**Expected behavior**
Loading to only appear when main thread is blocked 

**Steps To Reproduce**
https://github.com/h2oai/sales-engineering/blob/master/mtanco/wave/apps/client-data/app.py

The button is an example where I have not yet coded it's functionality, I would expect that when I click it nothing happens, but we get stuck in loading.
The Menu -> Home is an example where I have "changed" the site so we don't get stuck in loading:
```
    elif q.args.home:
        q.page['no_page'].items = []
        await q.page.save()
```

**Comment by lo5** [comment]
@mturoci - no technical reason - we'll have to implement dirty-tracking on the `Page` in Python-land, so icky. Not sure if it's worth the effort. 

If you think about it, this is equivalent to authoring a request handler in a non-Wave app, but not providing a response, which begs the question - why have the handler there in the first place? 

I can understand that a first-time user might be puzzled, but the same applies to a first time user of Django or Flask - if you don't respond to the browser, you don't see a response in the browser.

Look at it this way - 

Hiding the spinner (via an empty response) might be even worse for both first time users and advanced users - you will be unable to distinguish between (A) my app responded, and the UI did not change because the command produced the same result as before, and (B) my app did not respond because some `if-elif` somewhere has a bug in conditional logic.

At least with Peto's implementation, if the spinner does not go away, you know it's [B] without having to reach for a debugger.

So we need a strong reason and examples of apps where you'd want a button click or some command to not respond to the user.

**Comment by mturoci** [comment]
> I can understand that a first-time user might be puzzled, but the same applies to a first time user of Django or Flask - if you don't respond to the browser, you don't see a response in the browser.

Makes sense.

**Comment by mtanco** [comment]
I am comfortable closing this after this discussion - but I don't think I'm the only person that's going to be confused, think something is broken, etc. (At least one other people has asked on slack). So, yes this is working as expected but how can we make sure that people know this? Note in docs? Post in discourse? or just wait until the next person asks and explain it

**Comment by lo5** [comment]
We can keep this issue open. If it bothers others, we'll think about it again. As of today I think addressing it would result in worse UX than not addressing it.

**Comment by pelumiojebode** [comment]
Me X ...
??
??
U F
