### ISSUE TITLE
Rewrite script examples that use form inputs as apps

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#424]
The examples that use form inputs were authored as scripts instead of apps in the interest of time, but are going to confuse first-time authors. 

If an example use form inputs, we need to show how to handle those inputs in an app.

**Comment by dulajra** [comment]
Most of the Form examples are already written as Wave apps. Only the following examples are in the script format.

```
Text
Text / Size
Label
Link
Progress
Progres / Updating
Message Bar
Separator
Frame
Frame / Path
Template
Markup
```

I think this is because all of the above Form components are non-interactive. Interactive components like Form Button, Form Textbox are already in wave apps. @lo5 So do we still need to migrate above components also to wave apps?

**Comment by lo5** [comment]
Ah! Thanks for the analysis - we can close this.
