### ISSUE TITLE
Wave apps wouldnt run, Problem with venv/wave? (Image attached)

### ISSUE THREAD

**Issue by GuruPrasaathM** [h2oai/wave#435]
#### Wave SDK Version, OS

0.10.0 Win10 64 Bit
#### Issue

Returns some error whenever i try to my todo wave app as given in your doc/guide, Could the problem be because i am running another wave script parallelly? or is it something else, I am not really sure what to make of this error as it has to do something with h2oi wave's code and some multiprocessing module's code, Am i doing something wrong? Do i reinstall the asyncio module or try something else?

![WaveError](https://user-images.githubusercontent.com/56358942/102863606-d4a00600-4458-11eb-910f-9f3cb7194689.PNG)

**Comment by goldentom42** [comment]
Hi @GuruPrasaathM, thanks for trying H2O wave !

I am on Win10 Pro and was able to run several wave apps in parallel, so it's probably something else.

From your screenshot it seems you are trying to run the `todo` app from the `Scripts` directory, where the activation script of your `mypython` env is.

Sorry for the stupid question but is the todo.py script you are trying to run in the Scripts folder ?
Because I also tried starting the todo app from that folder and it works for me.

**Comment by GuruPrasaathM** [comment]
Hey @goldentom42  Thanks a lot for the response

Yes i was trying to run it in the scripts folder, for no particular reason

I think probably has to do with my installation or something else considering the same works for you, I guess i ll try it somewhere else, Btw, I got some other stuff working and your package has helped me really much to quickly build a school project after i almost messed up on a deadline

I really admire your work and wish the best of luck to you and your team :)

Thanks again!

**Comment by goldentom42** [comment]
@GuruPrasaathM, to ease my work on windows I use MiniConda, it may help get things more stable.
Thanks for your reply.
