### ISSUE TITLE
Layout/SVG rendering issues in flex layout

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#473]
This is a catch-all issue for layout/rendering issues holding up release 0.11.

**Grey Dashboard**: Footer renders on top of bottom row:

![2021-01-05-172540](https://user-images.githubusercontent.com/6334572/103719120-35f9c600-4f7d-11eb-8d23-fec7b9a1b027.png)

**Comment by lo5** [comment]
Red, Mint, Grey dashboards: SVG + flex causes wonky width/height, but not in all cases. e.g. they render fine in the other dashboards:

![2021-01-05-173929](https://user-images.githubusercontent.com/6334572/103719632-48283400-4f7e-11eb-8e43-409734e8b655.png)


Interestingly, setting a % (or fixed) width on the box "corrects" the issue, but is annoying from an API perspective:


![2021-01-05-173852](https://user-images.githubusercontent.com/6334572/103719707-73ab1e80-4f7e-11eb-81f9-cb637297e845.png)


![2021-01-05-173759](https://user-images.githubusercontent.com/6334572/103719687-65f59900-4f7e-11eb-9254-dc70afafa364.png)

**Comment by lo5** [comment]
This is still broken - needs investigation:

![2021-01-05-174523](https://user-images.githubusercontent.com/6334572/103719777-9e957280-4f7e-11eb-9c10-87cd70adc441.png)
![2021-01-05-174558](https://user-images.githubusercontent.com/6334572/103719780-a05f3600-4f7e-11eb-80ef-071914be9545.png)

**Comment by mturoci** [comment]
Managed to fix flex layout alignment and wonky width/height. Need to resolve window resizing as it broke with theses changes.

Grey dashboard footer:
The overflow is caused because incorrect size is set. `body` zone has five elements with sizes: `0`, `25%`, `25%`,  `25%`,  `25%`. That means that zones `top`, `middle`, `middle2`, `bottom` take up `100%` height together, but there is also a `title` with size `0` which causes undesired overflow. This can be fixed in 3 ways:
* don't specify the size at all
* specify explicit size for all
* specify for some, but leave space for the rest of the elements, in other words, don't specify full 100% e.g. `0`, `20%`, `25%`, `25%`, `25%` - leaves dynamic 5% for the first item.
