### ISSUE TITLE
Window icons don't work in Safari

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#548]
The meta_card's icon attribute fails to apply in Safari. Ref `examples/meta_icon.py`.

**Comment by mturoci** [comment]
Current solution correctly changes favicon `href` url (I verified in DOM). A few hacks tried with no luck:
* Manually create a new HTML node and replace the existing one to trigger favicon update instead of just editing the `href`.
* Remove favicon links from `index.html` completely and add them via JS within `meta.tsx`. Seems like webkit reads favicon during parsing phase only, meaning the `index.html` has to already have the correct favicons set when being downloaded.

Wasn't able to find a solution to make this work. Finally, found a brief mention in [this webkit bug report](https://bugs.webkit.org/show_bug.cgi?id=75877). Citing:

_... Since we quite purposefully don't allow dynamic changes/animations to the favicon ..._

Related [bug](https://bugs.webkit.org/show_bug.cgi?id=12892) - Safari sometimes favors root `favicon.ico` instead of the value provided in `link`.

This leaves us with the only option of directing app devs to replace `favicon.ico` that we ship with Go server and deprecate meta_card's `icon` prop. @lo5

**Comment by lo5** [comment]
Deprecation is out of question since this feature already works in other popular browsers. Let's add a note to the docstring indicating that this does not work in Safari.
