### ISSUE TITLE
Page selector using regex pattern or some attribute

### ISSUE THREAD

**Issue by gbakthavatchalam** [h2oai/wave#554]
When we have to route between different pages, we need to clean up the already existing cards and setup new cards on the page. For this, we need to explicitly use the `page name` to be able to clean the card up.

Also, when we show a list of cards on a page we use page names like `card_num_1, card_num_2, card_num_3` etc and we need to clean them up, we iteratively clean them one by one.

Current Usage Below
---------------------

```
del q.page['card_abc']
del q.page['card_xyz']
del q.page['card_def']
del q.page['card_ghi']
del q.page['card_jkl']
for i in range(q.client.no_of_cards):
    del q.page[f'card_num_{i}']
```

#### Describe the solution you'd like

Instead, if we have a way to select multiple cards using a regex pattern or some attribute, we can remove them all in one shot.
Or if the cards have a new attribute like class, may be we can have a jquery like selector to select cards and delete them in bulk.

Like 
```
del q.page['card_num_*']. # select and delete multiple using regex pattern
del q.page['.my_class_name']. # select and delete all cards with class name as `my_class_name`
```

**Comment by lo5** [comment]
What you're asking for will affect performance across the board if implemented on the server side. 

If you want a simpler way to clear cards when navigating between pages, you can do this:

```py
def add_card(q, name, card):
    if not q.client.cards:
        q.client.cards = set()
    q.client.cards.add(name)
    q.page[name] = card
    return card

def clear_cards(q):
    if not q.client.cards:
        return
    for name in q.client.cards:
        del q.page[name]
    q.client.cards = set()

```

And then use `add_card(q, 'foo', card)` instead of `q.page['foo'] = card` every time you want a "bulk-removable" card, and `clear_cards(q)` when you want to drop them.

If you want wild-card-ish behavior, make `q.client.cards` a dict-of-sets instead of a set.

**Comment by gbakthavatchalam** [comment]
Thank you @lo5
