### ISSUE TITLE
Allow justifying elements vertically

### ISSUE THREAD

**Issue by psinger** [h2oai/wave#556]
I would have the following two feature requests with respect to justification:

- Currently, it does not seem possible to justify elements vertically, only horizontally. This looks specifically odd for buttons or similar objects being placed in form cards if they cannot be vertically aligned (e.g., center).
- Extend the justification options of `ui.inline` to also allow `center` alignment.

**Comment by 5675sp** [comment]
Hello - are there any updates for the second bullet point?

**Comment by mturoci** [comment]
@5675sp `ui.inline` now supports `center` horizontal alignment.

**Comment by aalencar** [comment]
Hi @psinger, could you provide some form card examples with screenshots where vertical alignment is needed?

**Comment by psinger** [comment]
@aalencar sorry I do not have any example screenshots as this is quite an old issue, but having horizontal alignment would be something I regularly would like to have

**Comment by aalencar** [comment]
@psinger It's an old issue indeed. I understand how vertical alignment can be useful in general, and I had already started development but then we realized we don't have many concrete use cases to justify further development. If you have any recent code where you couldn't achieve the desired alignment, post it here so that we can prioritize this task.
