### ISSUE TITLE
ui.frame() overlaps/blocks elements in container.

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#558]
Reported by @mtanco 

Minimal repro: (thanks @tkmaker)

The frame overlaps the buttons in this repro, making the buttons un-clickable.

```py
@app('/')
async def test(q: Q):
    q.page['main'] = ui.form_card(box='1 1 -1 -1',  items=[
            ui.buttons([ui.button(name='home_button', label='About this App1', disabled=False)], justify='center'),
            ui.frame(content=' ', height="30px")
         ])
    await q.page.save()
```

Caused by absolute positioning on the frame: https://github.com/h2oai/wave/commit/4e1afb295adf5f6702791f8cde10320b27dca530

**Comment by mtanco** [comment]
Related, just for extra testing: Height of the frame is ignored and takes up the entire card, hiding other elements in general. Above buttons we're visible but not clickable because the frame was empty

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/4793561/107656971-88439c00-6c39-11eb-94ab-b0be45e5496d.png">


```
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):
    q.page['testing'] = ui.form_card(
        box='4 2 8 8',
        items=[
            ui.text_xl('This is Example Dot Com!'),
            ui.frame(path='http://example.com', height="100px")
        ]
    )

    await q.page.save()
```
