### ISSUE TITLE
Possibility to style components/cards more

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [h2oai/wave#655]
It would be nice to be able to add additional styling. Passing a color/background parameter for each card would be awesome. Or the possibility to inject custom CSS.

**Comment by mtanco** [comment]
Hi @AlexWennerDT, please checkout the demo video in this PR which is tentatively slated for release 0.15.0 - this shows off what will be possible with custom themes and the tool-app you can use to create your theme code to use in your app: https://github.com/h2oai/wave/pull/604

We have seen most interest in overall themes of apps rather than individually for different cards at this point

**Comment by AlexWennerDT** [comment]
Oh wow, this is an awesome feature! Super exciting to see you guys adding so many features. Using this Pythonic framework has been the best UI dev experience I have had thus far. Thanks for the hard work!

Alex Wenner | Digital Transformation Analyst | Flint Hills Resources |Office: (316) 226-8394| Cell: (660) 287-0646

**Comment by mturoci** [comment]
Resolved by https://github.com/h2oai/wave/issues/965
