### ISSUE TITLE
Events plot selects the full data series, when it is a line. 

### ISSUE THREAD

**Issue by fousasg** [h2oai/wave#738]
In the example code for plot events (see below) the example shows a bars graph. 
![Screenshot_20210414-170814_Webex Meet](https://user-images.githubusercontent.com/20576978/114854572-dd885f00-9ddc-11eb-8f82-57e715cef9ed.jpg)

When one of the bars is selected then just the selected data point is selected (see below).
![Screenshot_20210414-170751_Webex Meet](https://user-images.githubusercontent.com/20576978/114855081-7028fe00-9ddd-11eb-80fd-f28c98e67a65.jpg)

However, when the **type** of the plot is changed from **interval** to **line** then any selection returns the full data series.
![Screenshot_20210414-170722_Webex Meet](https://user-images.githubusercontent.com/20576978/114855349-c8f89680-9ddd-11eb-9e67-2f15788cc276.jpg)

**Comment by mturoci** [comment]
Seems like this is by design. G2 selects by shapes, not by hovered points. From their [docs](https://g2.antv.vision/zh/docs/api/general/event):
![image](https://user-images.githubusercontent.com/64769322/116874460-a954d100-ac19-11eb-9636-544e91cfb7ff.png)

I tried to look into the event object for possible work around, but no luck so far.

**Comment by lo5** [comment]
@fousasg This is by design. 

To allow selecting individual points, simply add a new `point` layer on top of the `line` layer:

```py
            plot=ui.plot([
                ui.mark(type='line', x='=product', y='=price', y_min=0),
                ui.mark(type='point', x='=product', y='=price', y_min=0), # Layer of point marks
            ]),
```
