### ISSUE TITLE
Improvements to tour.py

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#776]
Via @mturoci  #753

- [x] Split nav menu into subgroups (form / plots etc.) to make it easier for user when searching something.
- [x] Implement global search to quickly go to the example that user wants. This could be achieved by using either picker (not so great) or by #303 (better).
- [ ] Clean up all the examples and make them use only the minimum necessary card space (edit `box` attribute) so that it doesn't cause overflow within tour iframe even though content is short. In other words, prevent scrollbars where possible.
- [x] Distant future - integrate our online IDE and make the tour examples editable with live changes.

**Comment by yashraizada** [comment]
Can you give me more details on this? I would like to work on this.

**Comment by mturoci** [comment]
Hi @yashraizada. There is just a single point left which is

> Clean up all the examples and make them use only the minimum necessary card space (edit box attribute) so that it doesn't cause overflow within tour iframe even though content is short. In other words, prevent scrollbars where possible.

A single picture is worth more than 1000 words so:

![image](https://user-images.githubusercontent.com/64769322/193993627-bf268547-fb98-405b-9175-18e5613fd89f.png)

Should be rewritten to 

![image](https://user-images.githubusercontent.com/64769322/193993904-0cf6e13f-665f-44a5-a79d-a3c128f0d977.png)

You can also refactor code where necessary - where too long lines cause a horizontal scrollbar.

When done, please include before/after images in your PR.

[Dev env setup](https://wave.h2o.ai/docs/contributing#development-setup), then instead of button example run `wave run examples.tour --no-reload` and you are all set!

**Comment by JacksonIsaac** [comment]
Would like to work on this :) The part about scrollbar

**Comment by mturoci** [comment]
All yours @JacksonIsaac!

**Comment by JacksonIsaac** [comment]
Pretty straightforward fix I believe. Also I think you gave away the changes in your screenshot :D

Btw, I noticed that on my left pane, the py code doesn't show up. I tried disabling my extensions, but still it remains blank. Not sure if I do something differently, or perhaps it's my WSL

**Comment by mturoci** [comment]
Thanks @JacksonIsaac, note that the goal of this issue is to fix all the examples in similar fashion.

> Btw, I noticed that on my left pane, the py code doesn't show up. I tried disabling my extensions, but still it remains blank. Not sure if I do something differently, or perhaps it's my WSL

Interesting. Can you please check the browser console and see if there are any errors?

**Comment by JacksonIsaac** [comment]
Browser console complains about pyiodide. And I don't see it in the py/examples/requirements.txt file as well. Maybe that is one o the issue ?

**Comment by mturoci** [comment]
pyodide is a JS lib, so that's why it's not listed in requirements.txt. Can you please paste the whole console stacktrace?

**Comment by JacksonIsaac** [comment]
https://privatebin.net/?328cc19f439ad831#HCzSBUHD4dKbRmBRRY1TUeAMnKQBgqS4x5LQ43NMYsGo Here's the console log
