### ISSUE TITLE
Unable to Access Wave-ML Docs

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#778]
#### Wave SDK Version, OS
Current Wave documentation - v0.14

#### Actual behavior
Click the sub-module and get a 404: https://wave.h2o.ai/docs/api/h2o_wave_ml/index/ml

#### Expected behavior
Click the sub-module and end up on docs page: https://wave.h2o.ai/docs/api/h2o_wave_ml/ml/

#### Steps To Reproduce

1. Start in the Wave-ML section of the 0.14 release blog post: https://wave.h2o.ai/blog/release-0.14#wave-ml
2. Click Wave-ML
<img width="776" alt="image" src="https://user-images.githubusercontent.com/4793561/116838859-d73c0600-ab84-11eb-981c-2650af4f9af8.png">

3a. Click the first link `h2o_wave_ml` to be redirected to the page you're already on
3b. Click `h2o_wave_ml.ml` submodule to get a 404 https://wave.h2o.ai/docs/api/h2o_wave_ml/index/ml

**Comment by geomodular** [comment]
@mtanco thanks for catching this.

The error is not *Wave ML* related only. Try this, go here: https://wave.h2o.ai/docs/api/index and click on random submodule. You should get the same error. However, If you go through the left menu, you should get the page without error (`Package h2o_wave` -> `h2o_wave.core`).

The problem is that the direct link, after landing, is changed to contain the `/` i.e:

```
https://wave.h2o.ai/docs/api/index
```
is changed to
```
https://wave.h2o.ai/docs/api/index/
```

That is enough to mix up relative links submodules are pointing to.

IMO the issue should be resolved on the webserver site. There is no such misbehavior when docusaurus run locally. I don't know the details of how the page is served now but I guess there is some auto-slash option enabled.

Is it still served from github?

cc @lo5 @mturoci

**Comment by lo5** [comment]
We're on S3 now. See and https://github.com/facebook/docusaurus/issues/2394 and https://github.com/facebook/docusaurus/issues/3372
