### ISSUE TITLE
Meta Description and logo edit in ui.meta_card

### ISSUE THREAD

**Issue by sairaamv** [h2oai/wave#784]
If I share a website built by H2O Wave Dashboard, we get the website and logo description with H2O Wave

![image](https://user-images.githubusercontent.com/41129569/117096078-a24ad180-ad85-11eb-8b55-373c5f6eb5f2.png)

Here is one example. Can we edit that meta information?

-- thanks

**Comment by lo5** [comment]
The only way to do this is to edit `www/index.html` and modify the following tags:

```html
      <link rel="icon" href="/favicon.ico"/>
      <link rel="apple-touch-icon" href="/logo192.png"/>
      <meta name="description" content="Dashboard created using H2O Wave"/>
rel="stylesheet">
      <title>H2O Wave</title>
```

You can also replace `favicon.ico`, `logo192.png`, etc. if you want to change the default icon.

This is because the previews that show up in Slack / Discord / Twitter, etc. is built up from the `index.html` file, before the browser/UI has a chance to use your preferred values from the `meta_card`.
