### ISSUE TITLE
Project/Model card

### ISSUE THREAD

**Issue by sandruparo** [h2oai/wave#792]
The Current card does not support the attached design. 

1. The title of the card should be 20 px  
2. Need to maintain a status chip with an icon. 
3. Font weight could be able to define. 
4. " more " text should come right aligned. 
5. The entire card should be clickable.  

@lo5 @shanaka-rajitha @MartinBarus @mtanco 

![image](https://user-images.githubusercontent.com/9942408/117407525-4e2e2180-af2c-11eb-9ad3-58357084558f.png)

**Comment by lo5** [comment]
Apart from "The entire card should be clickable.", we should be able to repro this using a form_card() with ui.stats() and ui.inline(). WDYT @mturoci?

**Comment by mturoci** [comment]
@lo5 more or less:
![image](https://user-images.githubusercontent.com/64769322/117488013-26f74480-af6c-11eb-9eac-735d36ed19fe.png)

```py
from h2o_wave import Q, ui, main, app


@app('/demo')
async def serve(q: Q):
    if not q.client.initialized:
        q.page['meta'] = ui.meta_card(box='', theme='neon')
        q.client.initialized = True

    q.page['wizard'] = ui.form_card(box='1 1 2 3', items=[
        ui.inline(items=[
            ui.text_xl(content='model_m1'),
            ui.link(label='Dev', path='google.com'),
        ]),
        ui.stats(justify='between', items=[
            ui.stat(label='Total Records:', value='6847'),
            ui.stat(label='Total Alerts:', value='1234'),
        ]),
        ui.text(content='Some content ...'),
        ui.buttons(justify='between', name='btns', items=[
            ui.button(name='critical', label='Critical'),
            ui.button(name='more', label='more', link=True),
        ]),
    ])

    await q.page.save()
```

**Comment by sandruparo** [comment]
@mturoci  any luck on the font weight ? and status chip color ?

**Comment by mturoci** [comment]
> any luck on the font weight ?

I think we can tweak the `ui.inline` component as you see fit so that all the apps can benefit from it. What is the desired value?

> and status chip color ?

@lo5 I think this is a common request to control button colors, maybe we should expose `color` prop and calculate text color via [this](https://gomakethings.com/dynamically-changing-the-text-color-based-on-background-color-contrast-with-vanilla-js/).

**Comment by lo5** [comment]
> I think we can tweak the ui.inline component

Maybe you meant `ui.text()`?

@sandruparo, @shanaka-rajitha - Can we try to stick to a small number of pre-defined font size/weight combos that work well together? As @mturoci demonstrated above, it's simple to piece together elements to achieve varied layouts. It would be good to see a proposal for typography that we can then reuse across cards/components instead of providing making the size/weight user-tweakable. The overarching goal for Wave is to provide cards/components that look good without app developers having to spend much effort tweaking them.. 

>  I think this is a common request to control button colors,

Isn't that a [badge](https://getbootstrap.com/docs/5.0/components/badge/)? We probably needs a new component.

**Comment by sandruparo** [comment]
@lo5 I think you are right prithivi, better to introduce that ( badge ) as a separate new component. it's better to improve that with an icon also next to the label. 

@shanaka-rajitha is currently working on the typography and the size/weight too and he will give a proposal on that. i think it's better to define some sizes with it's weight so that the user can use it according to their needs ( based on the designs ).

**Comment by mturoci** [comment]
Closing as already possible.
