### ISSUE TITLE
Form items width control

### ISSUE THREAD

**Issue by sandruparo** [h2oai/wave#795]
The input fields width should be adjustable , currently it takes the whole body like a block element. we should make it flexible  to define by the dev.

![image](https://user-images.githubusercontent.com/9942408/117422248-05329900-af3d-11eb-8249-b7e873291c02.png)

@lo5 @shanaka-rajitha @MartinBarus @mtanco

**Comment by dulajra** [comment]
To add to this, the width should be customizable when the components are placed inline also. Currently the `ui.textbox` has a fixed width so that when the text is long the content is not fully readable. 
![Screenshot 2021-06-21 at 17 20 24](https://user-images.githubusercontent.com/12434380/122769235-06880d00-d2c2-11eb-8d52-77438bbdf345.png)

**Comment by mturoci** [comment]
@lo5 I feel like this could make sense for every form item (similar to how `visible` is implemented), that way simple designs like this
![image](https://user-images.githubusercontent.com/64769322/129567266-0208ce08-2a6e-44ea-83f0-43c513b866c4.png)

could be simply implemented within a `form_card`.

**Comment by lo5** [comment]
@mturoci +1, would be good to have on all form components.
