### ISSUE TITLE
mode='multicast' in wave app doesn't work

### ISSUE THREAD

**Issue by shrinidhin** [h2oai/wave#812]
I have begun with the documentation of h2oai Wave and I am executing the Tutorials. In the bean counter tutorial of Wave apps, while trying the mode='multicast; to maintain the sync at user level, the code doesn't seem to work and nothing happens. My Wave server is running fine and the code is exactly the same as given in the tutorial but I don't understand what is the issue. Kindly help me resolve the same,

`
@app('/bean_counter', mode='multicast')`

**Comment by lo5** [comment]
@shrinidhin - Thanks for reporting!

In general, the `multicast` mode only make sense if user auth is enabled, since there is no real concept of a "user" otherwise.

I've pushed a fix so that `multicast` works even if user auth is not enabled (to ease development / make the tutorials work). Will be out in 0.15.1.

**Comment by shrinidhin** [comment]
Thank you for your response!Could you elaborate more on what you mean by 'if user auth is enabled'?

**Comment by lo5** [comment]
I meant SSO: https://wave.h2o.ai/docs/security#single-sign-on

**Comment by shrinidhin** [comment]
Alright.Thank you!
